apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-wart-charts.fullname" . }}
  labels:
    {{- include "redis-wart-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-wart-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis-wart-charts.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redis-wart-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          args: ["--redis-address=redis-master.eliza.svc.cluster.local:6379", "--wart-name=wart1"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
            - name: healthhttp
              containerPort: 8787
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: healthhttp
          readinessProbe:
            httpGet:
              path: /
              port: healthhttp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
