{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hats-worker-charts.serviceAccountName" . }}
  labels:
{{ include "hats-worker-charts.labels" . | nindent 4 }}
{{- end -}}
